---
- name: Copy Auditbeat configuration.
  template:
    src: auditbeat.yml.j2
    dest: "/etc/auditbeat/auditbeat.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart auditbeat

- name: Ensure Auditbeat SSL key pair directory exists.
  file:
    path: "{{ auditbeat_ssl_dir }}"
    state: directory
  when: auditbeat_ssl_key_file

- name: Copy SSL key and cert for auditbeat.
  copy:
    src: "{{ item }}"
    dest: "{{ auditbeat_ssl_dir }}/{{ item | basename }}"
    mode: 0644
  with_items:
    - "{{ auditbeat_ssl_key_file }}"
    - "{{ auditbeat_ssl_certificate_file }}"
  notify: restart auditbeat
  when: auditbeat_ssl_key_file and auditbeat_ssl_certificate_file
