---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  become_user: root
  become_method: sudo
  roles:
    - role: ${ANSIBLE_ROLE_NAME}
      stop_service_auditd: false
      auditbeat_modules_conf:
        - module: file_integrity
          paths:
            - /bin
            - /usr/bin
            - /sbin
            - /usr/sbin
            - /etc
          exclude_files:
            - '(?i)\.sw[nop]$'
            - '~$'
            - '/\.git($|/)'
          scan_at_start: true
          scan_rate_per_sec: 50 MiB
          max_file_size: 100 MiB
          hash_types: [sha256]
          recursive: false
        - module: auditd
          resolve_ids: true
          failure_mode: silent
          backlog_limit: 8192
          rate_limit: 0
          include_raw_message: false
          include_warnings: false
          backpressure_strategy: auto
      auditbeat_enable_logging: true
      auditbeat_log_level: debug
