---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/common/yamllint
platforms:
  - name: molecule-centos-docker
    image: paulfantom/centos-molecule:7
    command: ""
    privileged: true
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    pid_mode: host
    capabilities:
      - SYS_ADMIN
      - AUDIT_CONTROL
      - AUDIT_READ
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: molecule-ubuntu-18-04-docker
    image: paulfantom/ubuntu-molecule:18.04
    command: ""
    privileged: true
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    pid_mode: host
    capabilities:
      - SYS_ADMIN
      - AUDIT_CONTROL
      - AUDIT_READ
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  playbooks:
    converge: ../common/playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: docker
verifier:
  name: testinfra
  directory: ../../tests
  lint:
    name: flake8
