---
driver:
  name: delegated
lint:
  name: yamllint
  options:
    config-file: molecule/common/yamllint
platforms:
  - name: dummy
provisioner:
  name: ansible
  playbooks:
    converge: ../common/playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: syntax
verifier:
  name: testinfra
  directory: ../tests
  lint:
    name: flake8
